name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main
      - test
  workflow_dispatch:

# Set permissions
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment per branch
concurrency:
  group: "pages-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: './frontend/package-lock.json'
      
      - name: Install dependencies
        working-directory: ./frontend
        run: npm install
      
      - name: Setup Build Cache
        uses: actions/cache@v3
        with:
          path: |
            frontend/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-
      
      # Add step to determine deployment path
      - name: Set deployment path
        id: set-path
        run: |
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            echo "DEPLOY_PATH=/trusted-travel-quick" >> $GITHUB_ENV
          else
            echo "DEPLOY_PATH=/trusted-travel-quick/test" >> $GITHUB_ENV
          fi
      
      - name: Build
        working-directory: ./frontend
        env:
          NEXT_PUBLIC_BASE_PATH: ${{ env.DEPLOY_PATH }}
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
          FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          FIREBASE_MEASUREMENT_ID: ${{ secrets.FIREBASE_MEASUREMENT_ID }}
        run: |
          npm run build
          # Ensure .nojekyll file exists to prevent GitHub Pages from ignoring files that begin with an underscore
          touch out/.nojekyll
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./frontend/out

  deploy:
    environment:
      # Configure environment based on branch
      name: ${{ github.ref == 'refs/heads/main' && 'github-pages' || 'github-pages-test' }}
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4